### ISSUE TITLE
old GPU on ggml CUDA, CUDA error 209 at ggml-cuda.cu:5284: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by makao007** [ggerganov/ggml#465]
Hi, I'm using a old GPU.
I can try run the whisper demo with CUDA but fail.
```
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce 940MX, compute capability 5.0
CUDA error 209 at D:\Download\ggml-master\ggml-master\src\ggml-cuda.cu:5284: no kernel image is available for execution on the device
```
Is there any way to support the old Nvidia GPU?

**Comment by makao007** [comment]
I updated file src/CMakeLists.txt
from:
`set_property(TARGET ggml  PROPERTY CUDA_ARCHITECTURES "52;61")`
to:
`set_property(TARGET ggml  PROPERTY CUDA_ARCHITECTURES "50;52;61")`
--
It works now.
